import { DocSection, PropTable, FeatureGrid, DocNote } from '../../../shared/DocComponents';

export function ParticleBackgroundViewDocs() {
  return (
    <div style={{ maxWidth: 860 }}>
      <DocSection title="Features">
        <FeatureGrid features={[
          { label: 'Deterministic seeded particle layout', color: 'var(--color-primary)' },
          { label: 'SVG-based, no canvas/JS animation loop', color: 'var(--color-success)' },
          { label: 'Configurable particle count', color: 'var(--color-info)' },
          { label: 'Custom accent color', color: 'var(--color-warning)' },
          { label: 'Content overlay via children', color: '#a855f7' },
          { label: 'Fixed height container', color: '#14b8a6' },
        ]} />
      </DocSection>

      <DocSection title="Props">
        <PropTable props={[
          { name: 'children', type: 'ReactNode', description: 'Optional content rendered above the particle layer, e.g. a hero message or empty-state copy.' },
          { name: 'count', type: 'number', default: '40', description: 'Number of particles rendered. Layout is deterministically seeded from this value, so the same count always produces the same arrangement.' },
          { name: 'color', type: 'string', default: 'var(--color-primary)', description: 'Fill color for all particles.' },
          { name: 'height', type: 'number', default: '240', description: 'Container height in pixels. Width fills the parent.' },
          { name: 'className', type: 'string', description: 'Additional class names on the outer container.' },
          { name: 'style', type: 'CSSProperties', description: 'Inline style override applied to the outer container.' },
        ]} />
      </DocSection>

      <DocNote type="info">
        Particle positions are generated by a simple seeded PRNG derived from count, not Math.random — so re-renders with the same count prop produce a stable, non-flickering layout instead of new random positions every render.
      </DocNote>

      <DocNote type="tip">
        Because animation runs entirely via SVG &lt;animate&gt; elements (not JS/rAF), this component has near-zero runtime CPU cost and is safe to use as a background behind many other animated components (e.g. CommandOrbView, RequestFlowView) without frame-rate competition.
      </DocNote>
      
      <DocSection
        title="DUI Sizing & Theming"
        description="ParticleBackgroundView does not read size, width, color, or borderRadius from the DuiProvider context — it is not part of the sized-component system and has no size prop to fall back to a provider default."
      >
        <DocNote type="info">
          ParticleBackgroundView is unaffected by <code>{'<DuiProvider>'}</code> size/color context. Style it directly via its own props (and CSS variables where documented above) rather than expecting provider-level sizing to apply.
        </DocNote>
      </DocSection>
      </div>
  );
}
