/** Common HTTP request headers for autocomplete */
export const HTTP_REQUEST_HEADERS = [
  'Accept',
  'Accept-Charset',
  'Accept-Encoding',
  'Accept-Language',
  'Accept-Ranges',
  'Access-Control-Allow-Credentials',
  'Access-Control-Allow-Headers',
  'Access-Control-Allow-Methods',
  'Access-Control-Allow-Origin',
  'Access-Control-Expose-Headers',
  'Access-Control-Max-Age',
  'Access-Control-Request-Headers',
  'Access-Control-Request-Method',
  'Age',
  'Authorization',
  'Cache-Control',
  'Connection',
  'Content-Disposition',
  'Content-Encoding',
  'Content-Language',
  'Content-Length',
  'Content-Location',
  'Content-Range',
  'Content-Security-Policy',
  'Content-Type',
  'Cookie',
  'Cross-Origin-Embedder-Policy',
  'Cross-Origin-Opener-Policy',
  'Cross-Origin-Resource-Policy',
  'Date',
  'DNT',
  'ETag',
  'Expect',
  'Expires',
  'Forwarded',
  'From',
  'Host',
  'If-Match',
  'If-Modified-Since',
  'If-None-Match',
  'If-Range',
  'If-Unmodified-Since',
  'Keep-Alive',
  'Last-Modified',
  'Link',
  'Location',
  'Max-Forwards',
  'Origin',
  'Permissions-Policy',
  'Pragma',
  'Proxy-Authenticate',
  'Proxy-Authorization',
  'Range',
  'Referer',
  'Referrer-Policy',
  'Retry-After',
  'Sec-Fetch-Dest',
  'Sec-Fetch-Mode',
  'Sec-Fetch-Site',
  'Sec-Fetch-User',
  'Server',
  'Set-Cookie',
  'Strict-Transport-Security',
  'TE',
  'Trailer',
  'Transfer-Encoding',
  'Upgrade',
  'Upgrade-Insecure-Requests',
  'User-Agent',
  'Vary',
  'Via',
  'WWW-Authenticate',
  'Warning',
  'X-Content-Type-Options',
  'X-Correlation-ID',
  'X-Forwarded-For',
  'X-Forwarded-Host',
  'X-Forwarded-Proto',
  'X-Frame-Options',
  'X-Request-ID',
  'X-Requested-With',
  'X-XSS-Protection',
];

/** Headers whose values should be masked by default */
export const SENSITIVE_HEADERS = [
  'authorization',
  'proxy-authorization',
  'cookie',
  'set-cookie',
  'x-api-key',
  'x-auth-token',
  'x-csrf-token',
  'x-xsrf-token',
];

/** Common header value suggestions keyed by lowercase header name */
export const HEADER_VALUE_SUGGESTIONS: Record<string, string[]> = {
  'content-type': [
    'application/json',
    'application/xml',
    'application/x-www-form-urlencoded',
    'multipart/form-data',
    'text/plain',
    'text/html',
    'text/css',
    'text/javascript',
    'application/javascript',
    'application/pdf',
    'application/octet-stream',
    'application/graphql',
    'application/ld+json',
    'application/vnd.api+json',
    'application/x-ndjson',
    'image/png',
    'image/jpeg',
    'image/gif',
    'image/svg+xml',
    'image/webp',
  ],
  'accept': [
    'application/json',
    'application/xml',
    'text/plain',
    'text/html',
    '*/*',
    'application/pdf',
    'image/*',
    'application/octet-stream',
    'application/vnd.api+json',
    'application/ld+json',
  ],
  'accept-encoding': [
    'gzip',
    'deflate',
    'br',
    'gzip, deflate',
    'gzip, deflate, br',
    'identity',
    '*',
  ],
  'accept-language': [
    'en-US',
    'en-US,en;q=0.9',
    'en-GB',
    'fr-FR',
    'de-DE',
    'es-ES',
    'zh-CN',
    'ja-JP',
    '*',
  ],
  'cache-control': [
    'no-cache',
    'no-store',
    'max-age=0',
    'max-age=3600',
    'max-age=86400',
    'no-cache, no-store, must-revalidate',
    'public, max-age=31536000',
    'private',
    'must-revalidate',
  ],
  'connection': [
    'keep-alive',
    'close',
    'upgrade',
  ],
  'content-encoding': [
    'gzip',
    'deflate',
    'br',
    'identity',
  ],
  'authorization': [
    'Bearer ',
    'Basic ',
    'Digest ',
    'Token ',
  ],
  'access-control-allow-origin': [
    '*',
    'null',
  ],
  'access-control-allow-methods': [
    'GET, POST, PUT, DELETE, OPTIONS',
    'GET, POST, OPTIONS',
    '*',
  ],
  'access-control-allow-headers': [
    'Content-Type, Authorization',
    'Content-Type, Authorization, X-Requested-With',
    '*',
  ],
  'x-content-type-options': [
    'nosniff',
  ],
  'x-frame-options': [
    'DENY',
    'SAMEORIGIN',
    'ALLOW-FROM',
  ],
  'x-xss-protection': [
    '0',
    '1',
    '1; mode=block',
  ],
  'strict-transport-security': [
    'max-age=31536000',
    'max-age=31536000; includeSubDomains',
    'max-age=31536000; includeSubDomains; preload',
  ],
  'referrer-policy': [
    'no-referrer',
    'no-referrer-when-downgrade',
    'origin',
    'origin-when-cross-origin',
    'same-origin',
    'strict-origin',
    'strict-origin-when-cross-origin',
    'unsafe-url',
  ],
  'content-disposition': [
    'inline',
    'attachment',
    'attachment; filename="file.pdf"',
  ],
  'transfer-encoding': [
    'chunked',
    'compress',
    'deflate',
    'gzip',
  ],
  'user-agent': [
    'Daakia/1.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    'curl/7.68.0',
    'PostmanRuntime/7.29.0',
  ],
};
