import { useRef, useState } from 'react';
import { InfoPopupView, ButtonView } from '@/dui';
import { InfoCircleIcon } from '@/icons/daakia-icons';
import { ExampleCard } from '../../../shared/ExampleCard';

// ─── Bearer Token Help ────────────────────────────────────────────────────────
function BearerTokenPopupDemo() {
  const [open, setOpen] = useState(false);
  const btnRef = useRef<HTMLButtonElement>(null);
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
      <span style={{ fontSize: 12, color: 'var(--color-text-secondary)' }}>Authorization</span>
      <button
        ref={btnRef}
        type="button"
        onClick={() => setOpen(v => !v)}
        style={{
          background: 'none', border: 'none', cursor: 'pointer',
          color: 'var(--color-text-muted)', padding: 0, display: 'flex',
        }}
        title="About Bearer tokens"
      >
        <InfoCircleIcon size={14} />
      </button>
      <InfoPopupView
        open={open}
        onClose={() => setOpen(false)}
        anchorEl={btnRef.current}
        title="Bearer Token"
        description="A bearer token is a cryptographic string included in the Authorization header to authenticate API requests."
        items={[
          { code: 'Authorization', description: 'Header name — must match exactly' },
          { code: 'Bearer <token>', description: 'Header value format — note the space after Bearer' },
        ]}
        footer="Tokens are usually JWTs generated by your auth server."
        wikiHref="https://daakia.dev/wiki/auth#bearer"
      />
    </div>
  );
}

// ─── API Key Location ─────────────────────────────────────────────────────────
function ApiKeyLocationDemo() {
  const [open, setOpen] = useState(false);
  const btnRef = useRef<HTMLButtonElement>(null);
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
      <span style={{ fontSize: 12, color: 'var(--color-text-secondary)' }}>API Key Location</span>
      <button
        ref={btnRef}
        type="button"
        onClick={() => setOpen(v => !v)}
        style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-text-muted)', padding: 0, display: 'flex' }}
      >
        <InfoCircleIcon size={14} />
      </button>
      <InfoPopupView
        open={open}
        onClose={() => setOpen(false)}
        anchorEl={btnRef.current}
        title="API Key Location"
        description="Choose where your API key will be sent with each request."
        items={[
          { code: 'Header', description: 'Sent as a request header (e.g. X-API-Key: your-key)' },
          { code: 'Query Param', description: 'Appended to the URL (e.g. ?api_key=your-key)' },
          { code: 'Cookie', description: 'Sent in the Cookie header — less common for public APIs' },
        ]}
        wikiHref="https://daakia.dev/wiki/auth#api-key"
      />
    </div>
  );
}

// ─── GraphQL Variables Help ───────────────────────────────────────────────────
function GraphQLVariablesDemo() {
  const [open, setOpen] = useState(false);
  const btnRef = useRef<HTMLButtonElement>(null);
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
      <span style={{ fontSize: 12, color: 'var(--color-text-secondary)' }}>Variables</span>
      <button
        ref={btnRef}
        type="button"
        onClick={() => setOpen(v => !v)}
        style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-protocol-graphql)', padding: 0, display: 'flex' }}
      >
        <InfoCircleIcon size={14} />
      </button>
      <InfoPopupView
        open={open}
        onClose={() => setOpen(false)}
        anchorEl={btnRef.current}
        title="GraphQL Variables"
        description="Variables let you pass dynamic values into your queries without hardcoding them in the operation string."
        items={[
          { code: '$userId', description: 'Declare in the operation: query GetUser($userId: ID!)' },
          { code: '{ "userId": "42" }', description: 'Provide the value as JSON in this panel' },
        ]}
        footer='Variables are sent in the "variables" field of the GraphQL request body.'
        wikiHref="https://daakia.dev/wiki/graphql#variables"
        width={340}
      />
    </div>
  );
}

// ─── Environment Variable Help ────────────────────────────────────────────────
function EnvironmentVarDemo() {
  const [open, setOpen] = useState(false);
  const btnRef = useRef<HTMLButtonElement>(null);
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
      <span style={{ fontSize: 12, color: 'var(--color-text-secondary)' }}>{'{{variable}}'} syntax</span>
      <button
        ref={btnRef}
        type="button"
        onClick={() => setOpen(v => !v)}
        style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-text-muted)', padding: 0, display: 'flex' }}
      >
        <InfoCircleIcon size={14} />
      </button>
      <InfoPopupView
        open={open}
        onClose={() => setOpen(false)}
        anchorEl={btnRef.current}
        title="Environment Variables"
        description="Use double-curly-brace syntax to reference environment variables anywhere in your request."
        items={[
          { code: '{{baseUrl}}', description: 'Resolved from the active environment at send time' },
          { code: '{{token}}',   description: 'Useful for auth tokens that rotate frequently' },
          { code: '{{userId}}',  description: 'Dynamic path or query parameters' },
        ]}
        footer="Switch environments to test against different servers without editing requests."
        wikiHref="https://daakia.dev/wiki/environments"
      />
    </div>
  );
}

// ─── Minimal popup (title only) ───────────────────────────────────────────────
function MinimalPopupDemo() {
  const [open, setOpen] = useState(false);
  const btnRef = useRef<HTMLButtonElement>(null);
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
      <ButtonView variant="ghost" size="sm" onClick={() => setOpen(v => !v)}>
        What is this?
      </ButtonView>
      <span ref={btnRef as unknown as React.RefObject<HTMLSpanElement>} />
      <InfoPopupView
        open={open}
        onClose={() => setOpen(false)}
        anchorEl={btnRef.current as unknown as HTMLElement}
        title="This is a minimal InfoPopupView with title only"
        width={260}
      />
    </div>
  );
}

// ─── Export ───────────────────────────────────────────────────────────────────
export function InfoPopupViewExamples() {
  return (
    <div>
      <ExampleCard
        title="Bearer Token Help"
        description="Click the info icon — popup anchors below it with title, description, code items, footer, and wiki link"
        code={`<InfoPopupView
  open={open} onClose={close} anchorEl={btnRef.current}
  title="Bearer Token"
  description="A bearer token is..."
  items={[{ code: 'Authorization', description: 'Header name' }]}
  footer="Tokens are usually JWTs."
  wikiHref="https://daakia.dev/wiki/auth#bearer"
/>`}
      >
        <BearerTokenPopupDemo />
      </ExampleCard>

      <ExampleCard
        title="API Key Location"
        description="Three code-badge items explaining Header, Query Param, and Cookie placements"
        code={`<InfoPopupView title="API Key Location"
  items={[
    { code: 'Header',      description: 'Sent as a request header' },
    { code: 'Query Param', description: 'Appended to the URL' },
    { code: 'Cookie',      description: 'Sent in the Cookie header' },
  ]}
/>`}
      >
        <ApiKeyLocationDemo />
      </ExampleCard>

      <ExampleCard
        title="GraphQL Variables Help"
        description="GraphQL accent color on icon, wider popup (width=340)"
        code={`<InfoPopupView title="GraphQL Variables"
  description="Variables let you pass dynamic values..."
  items={[{ code: '$userId', description: 'Declare in the operation' }]}
  width={340}
/>`}
      >
        <GraphQLVariablesDemo />
      </ExampleCard>

      <ExampleCard
        title="Environment Variable Help with Wiki Link"
        description="Three variable syntax examples + footer tip + wiki link at bottom"
        code={`<InfoPopupView title="Environment Variables"
  items={[
    { code: '{{baseUrl}}', description: 'Resolved from the active environment' },
    { code: '{{token}}',   description: 'Auth tokens that rotate frequently' },
  ]}
  wikiHref="https://daakia.dev/wiki/environments"
/>`}
      >
        <EnvironmentVarDemo />
      </ExampleCard>

      <ExampleCard
        title="Minimal Popup — Title Only"
        description="No description, no items, no footer — just the title bar"
        code={`<InfoPopupView open={open} onClose={close} title="This is a minimal InfoPopupView" width={260} />`}
      >
        <MinimalPopupDemo />
      </ExampleCard>
    </div>
  );
}
