#!/usr/bin/env node
/**
 * The README's component catalog, written from the manifest.
 *
 *   npm run catalog          # rewrite the block in README.md
 *   npm run catalog -- --check   # fail if it is out of date (for CI)
 *
 * Replaces everything between the two markers in README.md:
 *
 *   <!-- catalog:start -->  …generated…  <!-- catalog:end -->
 *
 * ── Why generate it ──
 *
 * The README spent its whole life saying "65+ components" — accurate on the
 * day it was written and wrong for every release after, because a hand-written
 * list of two hundred and thirty-eight names is a list nobody updates. This
 * reads `media/components.dark.json`, which `npm run shots` writes from the
 * running app, so the catalog is a fact about the library rather than a claim
 * about it. `--check` is the same comparison without the write, so a stale
 * README fails a build instead of shipping.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const README = path.join(ROOT, 'README.md');
const START = '<!-- catalog:start -->';
const END = '<!-- catalog:end -->';

const check = process.argv.includes('--check');

const DEMO = 'https://salilvnair.com/framework/dui/';
const RAW = 'https://raw.githubusercontent.com/salilvnair/dui/main';

const manifestPath = path.join(ROOT, 'media', 'components.dark.json');
if (!fs.existsSync(manifestPath)) {
  console.error(`No ${path.relative(ROOT, manifestPath)}. Run:  npm run shots`);
  process.exit(1);
}
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

const slug = (title) => title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/** A cell's worth of prose: one sentence, and no pipe to break the table. */
function short(desc) {
  if (!desc) return '';
  const firstSentence = desc.split(/(?<=[.!?])\s/)[0] || desc;
  const trimmed = firstSentence.length > 120 ? `${firstSentence.slice(0, 117).trimEnd()}…` : firstSentence;
  return trimmed.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}

function build() {
  const lines = [
    START,
    '',
    `<!-- Generated by \`npm run catalog\` from media/components.dark.json — do not edit by hand. -->`,
    '',
    `**${manifest.total} components** across ${manifest.groups.length} groups.`,
    `Every name links to that component running in the live demo; every group opens to a`,
    `contact sheet and a table of what is in it.`,
    '',
  ];

  for (const group of manifest.groups) {
    const items = manifest.components.filter(c => c.group === group);
    if (!items.length) continue;
    const sheet = `${RAW}/media/sheets/${slug(group)}.png`;

    lines.push(
      '<details>',
      `<summary><b>${group}</b> (${items.length})</summary>`,
      '',
      `![${group} — ${items.map(i => i.label).join(', ')}](${sheet})`,
      '',
      '| Component | What it is |',
      '| --- | --- |',
    );
    for (const c of items) {
      lines.push(`| [\`${c.label}\`](${DEMO}#/${c.id}) | ${short(c.desc)} |`);
    }
    lines.push('', '</details>', '');
  }

  lines.push(END);
  return lines.join('\n');
}

const readme = fs.readFileSync(README, 'utf8');
const from = readme.indexOf(START);
const to = readme.indexOf(END);
if (from === -1 || to === -1) {
  console.error(`README.md has no ${START} … ${END} block to fill.`);
  process.exit(1);
}

const next = readme.slice(0, from) + build() + readme.slice(to + END.length);

if (check) {
  if (next === readme) {
    console.log(`README catalog is current — ${manifest.total} components.`);
    process.exit(0);
  }
  console.error('README catalog is out of date. Run:  npm run catalog');
  process.exit(1);
}

fs.writeFileSync(README, next);
console.log(`README catalog rewritten — ${manifest.total} components in ${manifest.groups.length} groups.`);
