import { useState } from 'react';
import { EditorView, EditorLineNumbers } from '@/dui';
import type { EditorLanguage } from '@/dui';
import { ExampleCard } from '../../../shared/ExampleCard';

const SAMPLE_JSON = `{
  "userId": 42,
  "name": "Alice Wonderland",
  "role": "admin",
  "active": true,
  "tags": ["beta", "power-user"],
  "meta": { "joined": "2024-01-15", "requests": 1248 }
}`;

const SAMPLE_GQL = `query GetUser($id: ID!) {
  user(id: $id) {
    id
    name
    email
    posts(limit: 10) {
      id
      title
      createdAt
    }
  }
}`;

const SAMPLE_YAML = `openapi: "3.0.3"
info:
  title: Daakia API
  version: "1.0.0"
paths:
  /users:
    get:
      summary: List all users
      responses:
        "200":
          description: A list of users`;

const SAMPLE_RESPONSE = `{
  "status": "ok",
  "data": {
    "users": [
      { "id": 1, "name": "Alice" },
      { "id": 2, "name": "Bob" }
    ],
    "total": 2,
    "page": 1
  }
}`;

const LONG_LINE_TEXT = `// Word wrap demo: long lines that would normally require horizontal scrolling are wrapped to the next line, improving readability.
const result = await fetch("https://api.example.com/users?limit=100&offset=0&sort=createdAt&order=desc&filter=active", { method: "GET", headers: { "Authorization": "Bearer token123" } });`;

const SAMPLE_JS = `async function fetchUsers(token) {
  const res = await fetch('https://api.example.com/users', {
    method: 'GET',
    headers: { Authorization: \`Bearer \${token}\` },
  });
  if (!res.ok) throw new Error(\`HTTP \${res.status}\`);
  const data = await res.json();
  return data.users;
}`;

const SAMPLE_XML = `<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <auth:Token xmlns:auth="urn:auth">Bearer eyJhbGci...</auth:Token>
  </soap:Header>
  <soap:Body>
    <GetUserRequest xmlns="urn:example.com">
      <userId>42</userId>
    </GetUserRequest>
  </soap:Body>
</soap:Envelope>`;

const SAMPLE_PLAIN = `User Report — 2024-01-15
========================
Total users:   1,248
Active:        1,031 (82.6%)
Inactive:        217 (17.4%)

Top roles:
  1. viewer      812
  2. editor      298
  3. admin       138

Generated by Daakia API Client v2.1.0`;

// Shared editorOptions for line numbers
const WITH_LINE_NUMBERS = { lineNumbers: EditorLineNumbers.ON };

export function EditorViewExamples() {
  const [jsonBody,   setJsonBody]   = useState(SAMPLE_JSON);
  const [gqlQuery,   setGqlQuery]   = useState(SAMPLE_GQL);
  const [yamlConfig, setYamlConfig] = useState(SAMPLE_YAML);
  const [customLang, setCustomLang] = useState<EditorLanguage>('json');

  const langOptions: { value: EditorLanguage; label: string }[] = [
    { value: 'json',       label: 'JSON' },
    { value: 'graphql',    label: 'GraphQL' },
    { value: 'yaml',       label: 'YAML' },
    { value: 'javascript', label: 'JavaScript' },
    { value: 'xml',        label: 'XML' },
    { value: 'plaintext',  label: 'Plain Text' },
  ];

  return (
    <div>
      <ExampleCard
        title="JSON Request Body Editor"
        description="Editable JSON body with syntax highlighting and line numbers"
        code={`<EditorView
  value={jsonBody}
  onChange={setJsonBody}
  language="json"
  height="180px"
  editorOptions={{ lineNumbers: EditorLineNumbers.ON }}
/>`}
        noPad
      >
        <EditorView
          value={jsonBody}
          onChange={setJsonBody}
          language="json"
          height="180px"
          editorOptions={WITH_LINE_NUMBERS}
        />
      </ExampleCard>

      <ExampleCard
        title="GraphQL Query Editor"
        description="GQL syntax highlighting — language='graphql' enables field completion"
        code={`<EditorView
  value={gqlQuery}
  onChange={setGqlQuery}
  language="graphql"
  height="200px"
  editorOptions={{ lineNumbers: EditorLineNumbers.ON }}
/>`}
        noPad
      >
        <EditorView
          value={gqlQuery}
          onChange={setGqlQuery}
          language="graphql"
          height="200px"
          editorOptions={WITH_LINE_NUMBERS}
        />
      </ExampleCard>

      <ExampleCard
        title="YAML Config Editor"
        description="OpenAPI / environment config editor in YAML mode"
        code={`<EditorView
  value={yamlConfig}
  onChange={setYamlConfig}
  language="yaml"
  height="200px"
  editorOptions={{ lineNumbers: EditorLineNumbers.ON }}
/>`}
        noPad
      >
        <EditorView
          value={yamlConfig}
          onChange={setYamlConfig}
          language="yaml"
          height="200px"
          editorOptions={WITH_LINE_NUMBERS}
        />
      </ExampleCard>

      <ExampleCard
        title="Read-Only Response Viewer"
        description="readOnly=true — display-only mode for response bodies and logs"
        code={`<EditorView
  value={SAMPLE_RESPONSE}
  language="json"
  height="160px"
  readOnly
  editorOptions={{ lineNumbers: EditorLineNumbers.ON }}
/>`}
        noPad
      >
        <EditorView
          value={SAMPLE_RESPONSE}
          language="json"
          height="160px"
          readOnly
          editorOptions={WITH_LINE_NUMBERS}
        />
      </ExampleCard>

      <ExampleCard
        title="Word Wrap On"
        description="wordWrap=true prevents horizontal scrolling for long single-line content"
        code={`<EditorView
  value={longText}
  language="javascript"
  height="100px"
  wordWrap
/>`}
        noPad
      >
        <EditorView
          value={LONG_LINE_TEXT}
          language="javascript"
          height="100px"
          wordWrap
        />
      </ExampleCard>

      <ExampleCard
        title="Custom fontSize and Height"
        description="fontSize overrides the DUI size token — use for dense logs or large editors"
        code={`// Dense log viewer
<EditorView value={text} language="plaintext" height="80px" fontSize={10} />

// Comfortable full-page editor
<EditorView value={text} language="json" height="300px" fontSize={14}
  editorOptions={{ lineNumbers: EditorLineNumbers.ON }} />`}
        noPad
      >
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <div style={{ padding: '6px 12px', fontSize: 10, color: 'var(--color-text-muted)', background: 'color-mix(in srgb, var(--color-surface-border) 30%, transparent)' }}>
            fontSize=10 (dense)
          </div>
          <EditorView
            value={SAMPLE_JSON}
            language="json"
            height="80px"
            fontSize={10}
          />
          <div style={{ padding: '6px 12px', fontSize: 10, color: 'var(--color-text-muted)', background: 'color-mix(in srgb, var(--color-surface-border) 30%, transparent)', borderTop: '1px solid var(--color-surface-border)' }}>
            fontSize=14 (comfortable)
          </div>
          <EditorView
            value={SAMPLE_JSON}
            language="json"
            height="140px"
            fontSize={14}
            editorOptions={WITH_LINE_NUMBERS}
          />
        </div>
      </ExampleCard>

      <ExampleCard
        title="Language Switcher"
        description="Switch language mode dynamically — useful for multi-format body editors"
        code={`const [lang, setLang] = useState<EditorLanguage>('json');

<EditorView value={body} language={lang} height="160px" />`}
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
            {langOptions.map(opt => (
              <button
                key={opt.value}
                type="button"
                onClick={() => setCustomLang(opt.value)}
                style={{
                  padding: '3px 10px', borderRadius: 5, fontSize: 11, cursor: 'pointer',
                  border: '1px solid var(--color-surface-border)',
                  background: customLang === opt.value ? 'var(--color-primary)' : 'var(--color-surface)',
                  color: customLang === opt.value ? '#fff' : 'var(--color-text-secondary)',
                  fontFamily: 'inherit',
                }}
              >
                {opt.label}
              </button>
            ))}
          </div>
          <EditorView
            value={
              customLang === 'graphql'  ? SAMPLE_GQL   :
              customLang === 'yaml'     ? SAMPLE_YAML  :
              customLang === 'javascript' ? SAMPLE_JS  :
              customLang === 'xml'      ? SAMPLE_XML   :
              customLang === 'plaintext' ? SAMPLE_PLAIN :
              SAMPLE_JSON
            }
            language={customLang}
            height="160px"
            editorOptions={WITH_LINE_NUMBERS}
          />
        </div>
      </ExampleCard>

      <ExampleCard
        title="Size Variants"
        description="size token controls font size — sm=11px, md=12px, lg=13px, xl=14px"
        code={`<EditorView value={code} language="json" size="sm" height="80px" />
<EditorView value={code} language="json" size="md" height="80px" />
<EditorView value={code} language="json" size="lg" height="80px" />
<EditorView value={code} language="json" size="xl" height="80px" />`}
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {(['sm', 'md', 'lg', 'xl'] as const).map(s => (
            <div key={s}>
              <div style={{ fontSize: 10, color: 'var(--color-text-muted)', marginBottom: 4 }}>size="{s}"</div>
              <EditorView value={SAMPLE_JSON} language="json" size={s} height="70px" readOnly />
            </div>
          ))}
        </div>
      </ExampleCard>
    </div>
  );
}
